name: Lint Code Base

on: push

jobs:
  run-lint:
  
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Java Version
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
          
      
      - name: Grant Execute Permissions for Gradlew
        run: chmod +x gradlew
        
      - name: Clean the Project
        run: ./gradlew clean
        
      - name: Build the Project
        run: ./gradlew assemble
        
     # Upload Artifact Build
     # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/
