name: Build

env:
  # The name of the main module repository
  main_project_module: app
  
  #Name of the Repository
  repository_name: My Demo Github Actions

on: [push,pull_request]

jobs:
  run-lint:
    name: Build Project
    runs-on: ubuntu-latest
    

    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Java Version
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
          
      
      - name: Grant Execute Permissions for Gradlew
        run: chmod +x gradlew
        
      - name: Clean the Project
        run: ./gradlew clean
        
      - name: Build the Project
        run: ./gradlew assemble
