name: Lint Code Base

on: push

jobs:
  run-lint:
  
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Java Version
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: 'temurin'
          cache: gradle
          
      
      - name: Grant Execute Permissions for Gradlew
        run: chmod +x gradlew
        
      - name: Clean the Project
        run: ./gradlew clean
        
      - name: Build the Project
        run: ./gradlew assemble
